# Generated by Django 2.1.4 on 2018-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181207_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Admin')], default=0, null=True),
        ),
    ]
