# Generated by Django 2.1.3 on 2018-12-04 12:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('cheese', 'Cheese'), ('chicken', 'Chicken'), ('mushroom', 'Mushroom')], default='cheese', max_length=15, verbose_name='Пицца')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
            ],
        ),
    ]
