# Generated by Django 2.1.4 on 2018-12-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name_slug',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('cheese', 'Cheese'), ('chicken', 'Chicken'), ('mushroom', 'Mushroom')], default='cheese', max_length=15, verbose_name='Pizza'),
        ),
    ]
