# Generated by Django 2.1.4 on 2018-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_pizza_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name_slug',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
