# Generated by Django 2.1.4 on 2018-12-08 09:15

from decimal import Decimal
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_pizzatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='pizza_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='name_slug',
            field=models.CharField(default='', max_length=150),
        ),
    ]
