# Generated by Django 2.1.4 on 2018-12-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181208_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzatype',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('big', 'Big'), ('middle', 'Middle'), ('small', 'Small')], default='big', max_length=200),
        ),
    ]
