# Generated by Django 2.1.4 on 2018-12-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181208_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PizzaType'),
        ),
    ]
