# Generated by Django 2.1.4 on 2018-12-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181211_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PizzaType'),
        ),
    ]
